### ISSUE TITLE
Add application structure example

### ISSUE THREAD

**Issue by jaguililla** [hexagonkt/hexagon#171]
This could be a perfect task to start working on the project. If you would like to get involved or just play with a different toolkit for HTTP services, keep reading!

Your task will be to code an example demonstrating the structure of a simple application following this [Spark tutorial](http://sparkjava.com/tutorials/application-structure).

To get familiar with the project and set things up, you should read the [contributing](https://github.com/hexagonkt/hexagon/blob/master/contributing.md) document first. If something is not clear or doesn't work right, don't worry and post a comment, I will help you with that (and fix the document for the next one :wink:).

This exercise will give you a grasp on the project to further propose or develop improvements (if you are willing to continue committing code).

To complete this task:

- [ ] Code the service following [this Spark tutorial](http://sparkjava.com/tutorials/application-structure)
- [ ] Create a Pull Request to https://github.com/hexagonkt/application_structure from your project
- [ ] As an optional addition, you can add [Codecov](https://codecov.io) test coverage report inside the Travis CI pipeline

For reference, you can check this other example: https://github.com/hexagonkt/real_world. And of course, I will help you with it if you ask me (as I already did developments like this).

Have fun, and happy coding!

**Comment by kr9s8n1** [comment]
@jaguililla I'd like to contribute to Hexagon and would like to take this up as my first issue.

**Comment by jaguililla** [comment]
You are very welcome! thanks for your support :)

**Comment by aljacinto** [comment]
@jaguililla I'll try this one

**Comment by jaguililla** [comment]
Great @aljacinto ! I'll assign it to you

**Comment by jaguililla** [comment]
Hello, I'm just reviewing the Hacktoberfest issues still open. If you didn't finish the task, but still you want to commit what you've done. Come on, any help will be welcomed and I can finish the remaining part of the task :slightly_smiling_face: 

Next week I will proceed to update this task status and assignees. Thanks!

**Comment by aljacinto** [comment]
@jaguililla I didn't get a chance to look at this one but still want to work on it.  I would still like to work on it, just need more time.  I should have something by the end of the week.  Let me know if that's ok.

**Comment by jaguililla** [comment]
Ok, I appreciate the effort... However, if you can not continue no worries (I understand this is just for fun :) Take the time you want

**Comment by aljacinto** [comment]
@jaguililla you can take off my name, just can't find the time these days :)

**Comment by jaguililla** [comment]
Ok, thanks for your contribution to the API documentation. I hope you find the time and motivation to contribute to this project again :) My pleasure!

**Comment by jaguililla** [comment]
This tutorial is very similar to other ones, it can be skipped.
