### ISSUE TITLE
Create a Maven parent POM

### ISSUE THREAD

**Issue by jaguililla** [hexagonkt/hexagon#178]
This is an easy task to start with, it involves little coding as it is mostly scaffolding.

The purpose is to extract all common Kotlin and Hexagon configuration from [Maven Starter POM] to the [hexagon_starters](https://github.com/hexagonkt/hexagon/tree/master/hexagon_starters) module.

[Maven Starter POM]: https://github.com/hexagonkt/maven_starter/blob/master/pom.xml
[hexagon_starters]: https://github.com/hexagonkt/hexagon/tree/master/hexagon_starters

To get familiar with the project and set things up, you should read the [contributing](https://github.com/hexagonkt/hexagon/blob/master/contributing.md) document first. If something is not clear or doesn't work right, don't worry and post a comment, I will help you with that (and fix the document for the next one :wink:).

The steps to fulfill this issue are:

- [ ] Extract settings from [Maven Starter POM] project into a file named `maven_parent/pom.xml` inside the [hexagon_starters] module
- [ ] Update [hexagon_starters] `build.gradle` to publish the newly created POM to Bintray on the release
- [ ] Add a documentation page in the `hexagon_site` module 

Of course, you can contact me anytime if you have doubts. Thanks, and happy coding!

**Comment by 0001vrn** [comment]
Hi @jaguililla
I would like to take this up. I will be needing a little bit of help wrt docs being added in the `hexagon_site` module.

**Comment by jaguililla** [comment]
No worries, I'm available via Slack if you need advice

**Comment by mihinduranasinghe** [comment]
I need a help, How should i update build.gradle ?

**Comment by jaguililla** [comment]
You can take a look at the `gradle/bintray.gradle` file. There it includes source and documentation JARs to be plubished along the classes, maybe it helps you ;)

**Comment by mihinduranasinghe** [comment]
Thank you very much . I will try again

Thanks & regards !

Mihindu Ranasinghe
Treasurer
IEEE Student Branch
BSc. Software Engineering | University Of Kelaniya

Mobile : +94768416637

**Comment by jaguililla** [comment]
Hello, I'm just reviewing the Hacktoberfest issues still open. If you didn't finish the task, but still you want to commit what you've done. Come on, any help will be welcomed and I can finish the remaining part of the task :slightly_smiling_face: 

Next week I will proceed to update this task status and assignees. Thanks!
