### ISSUE TITLE
Fix API documentation edit link

### ISSUE THREAD

**Issue by jaguililla** [hexagonkt/hexagon#180]
Edit link doesn't lead to the file with the documentation and title is always Home.

Take this generated page as an example: https://hexagonkt.com/port_http_server/com.hexagonkt.http.server The [edit button](https://github.com/hexagonkt/hexagon/edit/master/hexagon_site/pages/port_http_server/com.hexagonkt.http.server/index.md) (the one with a pencil icon on top right position) doesn't take you to the correct file to edit that documentation.

Also, the title of the page is **Home** where it should be the package name (and in the case of a class or a method, its name).

This is a tricky issue and involves a little bit of research, and maybe requires some unavailable features in the tools used to generate the documentation [Dokka], [MkDocs] and [MkDocs Material Theme].

To give a little bit of context: the site generation is done from source code files and extra Markdown files. [Dokka] generates the Markdown for API classes, packages and modules, these are processed to fit in [MkDocs] using [Gradle] build scripts, and finally the documentation is compiled using the [MkDocs Material Theme] to a static site. This processing is done in the [hexagon_site] module (check the module for further reference).

The purpose of this process is to keep the source of the documentation close to the code and with the bare minimum number of files to be able to keep it up to date with the minimum effort.

To fix this issue, I haven't got a good solution yet, but a proposal would be:

1. Check if [MkDocs] allows front matter data (key/value pairs in `.md` files) passed to the rendering engine.
2. Find out if [MkDocs Material Theme] checks one of those keys to render the *edit* button.
3. If so, add Kotlin or Gradle code in the build logic to obtain the class file to which the `.md` belongs and set it in the `.md` file (maybe [Dokka] can do this though).
4. Check everything works smoothly and go for a beer.

If you read this issue and you came up with a better solution... I'm all ears!

[Dokka]: https://github.com/Kotlin/dokka
[MkDocs]: https://www.mkdocs.org
[MkDocs Material Theme]: https://squidfunk.github.io/mkdocs-material
[Gradle]: https://gradle.org
[hexagon_site]: https://github.com/hexagonkt/hexagon/tree/master/hexagon_site

**Comment by squidfunk** [comment]
Unrelated to this issue - just wanted to say: I'm the author of [mkdocs-material](https://squidfunk.github.io/mkdocs-material/) and LOVE what you made of the hero feature in `index.md`! I didn't know you could embed HTML into front matter. Pretty awesome.

**Comment by jaguililla** [comment]
Thanks @squidfunk ! I'm a big fan of your theme... it is outstanding :) Do you have a list of projects using it?

**Comment by squidfunk** [comment]
@jaguililla thanks! Glad to hear that. There's not really a list, no, but there are actually many projects using it :-)

**Comment by jaguililla** [comment]
If you ever make a list like "Sites done with mkdocs-material" tell me! I would like to be there :)

**Comment by nicolaic** [comment]
This issue appears to have already been fixed. Just commenting so it can be closed. :)

**Comment by jaguililla** [comment]
Unfortunately, it is not fixed... it is a challenging one. I just updated the description to give more details, so if you feel like you can do it... go ahead ;)

**Comment by aljacinto** [comment]
@jaguililla I generated and serve this locally.  I noticed that some links are working and some don't.  But the ones that are not working are not in github, not in hexagon_site module anyway.  They are moved and renamed from their project to hexagon_site.

Is the solution to pass the edit URLs for each page and change the link?

**Comment by jaguililla** [comment]
The missing pages are the ones generated by Dokka (it generates more than one page for a single file). It would be great to link the Kotlin source that generated a given Markdown page.

I don't know if Dokka currently provides this functionality :/

**Comment by aljacinto** [comment]
@jaguililla I think we can make this work, here are the steps

1. Use [metadata extension](https://squidfunk.github.io/mkdocs-material/extensions/metadata/#__source) of material mkdocs by modifying mkdocs.yml
2. Include metadata in md files through gradle or dokka like you mentioned above.  Example:

    ```
    edit_url: edit/master/port_http_server/src/main/kotlin/com/hexagonkt/http/server/Call.kt

    [com.hexagonkt.http.server](./index.md)

    ## Package com.hexagonkt.http.server

    ```
3. Override content template block in ```hexagon_site/mkdocs/main.html``` to use our meta.edit_url

    ```
    {% block content %}
      {% if config.repo_url and page.meta.edit_url %}
        <a href="{{ config.repo_url + page.meta.edit_url }}" title="{{ lang.t('edit.link.title') }}" class="md-icon md-content__icon">&#xE3C9;</a>
      {% endif %}
        ....[copy from mkdocs-material]
    {% endblock %}
    ```

There is also an alternative if you click on the mkdocs material link, look at Linking sources section.  We can set metadata:

```
path: tree/master/docs/extensions
source: metadata.md
```

You'll get a button way down where you can click to take you to the source.  Looks better than the pen, the only thing is it at the very bottom.  If we want that above then simply override the content block like above.

**Comment by aljacinto** [comment]
@jaguililla any feedback on the above solution?  Thanks

**Comment by jaguililla** [comment]
Sorry @aljacinto I just forgot :( I'll look into it this weekend (today or tomorrow tops)

**Comment by jaguililla** [comment]
Looks good to me... The difficulty I see is how to include the data inside the .md (generated by Dokka)

**Comment by aljacinto** [comment]
I don't see anything in dokka for that, you would think they'll have something for metadata but nothing.

**Comment by jaguililla** [comment]
The only way that I see is to manually process the Dokka generated `.md` in the build script to add the corresponding source file. It is feasible, but tricky.

**Comment by aljacinto** [comment]
Here's the answer from dokka:

None that I'm aware of right now, you can add it manually or write a script for that. You can also edit the StructuredFormatService or maybe even the FileGenerator itself, however this change will be much easier after the next release, which will introduce pluggability.

I can simply write a script that translate the output path to relative path i.e go through the generated md, look at the path and generate the edit_url from there.  For example:

```./hexagon_site/content/port_store/com.hexagonkt.store.hashmap/-hash-map-mapper/to-store.md```

will have metadata of 

```edit_url: edit/master/port_store/src/main/kotlin/com/hexagonkt/store/hashmap/HashMapMapper.kt```

Let me know if I should try.

**Comment by jaguililla** [comment]
Absolutely! I think it is feasible to resolve it that way, it would be harder for extension function's API (they have an extra directory with the receiver name).

But to me it is a great solution, if you want to take this task it would be great!

**Comment by jaguililla** [comment]
I'll assign this to you and update the board... If you change your mind, just tell me and I will put this back on TODO... Thanks for your help, your research on the subject was pretty awesome :)

**Comment by aljacinto** [comment]
@jaguililla you're right that the extension are tricky and getting me trouble, for example:

this `hexagon/hexagon_site/content/hexagon_core/com.hexagonkt.helpers/java.time.-local-time/to-number.md` should map to `hexagon_core/src/main/kotlin/com/hexagonkt/helpers/Dates.kt` but there is no `Dates` in path anywhere

**Comment by jaguililla** [comment]
Do not force yourself to get to the perfect solution... If it works for a good amount of classes, it is worthy (as now is not working for any API documentation editing) :slightly_smiling_face: If you do a PR with a partial solution it is OK for me to review it and merge it.

However, if you go for the PR, note the limitations in a TODO to be aware that eventually it should be solved.

For me, the perfect solution would come from Dokka. Next release they will allow plugins, so it could be a good opportunity to add that behavior directly into Dokka.

You provided a great solution. And it is a tricky issue... a lot of moving parts. Thank you!

**Comment by aljacinto** [comment]
PR created, I think I covered everything except for the one above.  Let me know.

**Comment by jaguililla** [comment]
Merged! Thanks! I'll check it locally, and we'll see in the next release ;)
