### ISSUE TITLE
Add HashMap Store in `port_storage`

### ISSUE THREAD

**Issue by jaguililla** [hexagonkt/hexagon#209]
The store port defines a minimum set of operations to store and fetch data objects from a given data store (Ie: a relational DB or a NoSQL DB).

A minimum implementation backed by a `HashMap` could be enough to start prototyping an application and later replace it by other implementation. It would also serve to created "cached stores".

As it wouldn't have any extra dependencies, it would be ok to place this new implementation directly inside the `port_store` module (on its own package).

To test this store, the same tests as in `MongoDbStoreTest` can be used (copying the class and renaming it). Or even better, the `MongoDbStoreTest` test class can be parametrized to use any other type and allow client applications to use it for their own tests (including this class in the `com.hexagonkt:port_store:<version>:test` dependency). You can check how to it's done in `com.hexagonkt:port_http_server:<version>:test`.

**Comment by JohanneA** [comment]
I can give this one a go 😄

**Comment by jaguililla** [comment]
Awesome!
