### ISSUE TITLE
Create Contact application example

### ISSUE THREAD

**Issue by jaguililla** [hexagonkt/hexagon#211]
This could be a perfect task to start working on the project. If you would like to get involved or just play with a different toolkit for HTTP services, keep reading!

Your task will be to code a simple Contact Application following the very same [Spark tutorial](http://sparkjava.com/tutorials/cloud-contact-app).

To get familiar with the project and set things up, you should read the [contributing](https://github.com/hexagonkt/hexagon/blob/master/contributing.md) document first. If something is not clear or doesn't work right, don't worry and post a comment, I will help you with that (and fix the document for the next one :wink:).

This exercise will give you a grasp on the project to further propose or develop improvements (if you are willing to continue committing code).

To complete this task:

- [ ] Code the service following [this Spark tutorial](http://sparkjava.com/tutorials/cloud-contact-app)
- [ ] Create a Pull Request to https://github.com/hexagonkt/contact_application from your project
- [ ] As an optional addition, you can add [Codecov](https://codecov.io) test coverage report inside the Travis CI pipeline

For reference, you can check this other example: https://github.com/hexagonkt/real_world. And of course, I will help you with it if you ask me (as I already did developments like this).

Have fun, and happy coding!

**Comment by Fantast** [comment]
I'd like to work on this as part of #hacktoberfest

**Comment by jaguililla** [comment]
Thanks! Just let me know if you need anything

**Comment by Fantast** [comment]
@jaguililla Can you create an initial commit in that repo? Otherwise, I can't create a fork on an empty repository...

**Comment by jaguililla** [comment]
Sorry, I din't knew. Done!

**Comment by Fantast** [comment]
@jaguililla I've finally finished this. Sorry for taking so long, I wasn't able to work hard enough on this :(

**Comment by jaguililla** [comment]
On the contrary... thanks for your contribution, this is only done for fun, I appreciate the effort :slightly_smiling_face: . I'll update the examples page to link to your example. Thanks again!
