### ISSUE TITLE
Develop Twitter clone example

### ISSUE THREAD

**Issue by jaguililla** [hexagonkt/hexagon#212]
This could be a perfect task to start working on the project. If you would like to get involved or just play with a different toolkit for HTTP services, keep reading!

Your task will be to code a Twitter clone example following the very same [Spark tutorial](http://sparkjava.com/tutorials/twitter-clone).

To get familiar with the project and set things up, you should read the [contributing](https://github.com/hexagonkt/hexagon/blob/master/contributing.md) document first. If something is not clear or doesn't work right, don't worry and post a comment, I will help you with that (and fix the document for the next one :wink:).

This exercise will give you a grasp on the project to further propose or develop improvements (if you are willing to continue committing code).

To complete this task:

- [ ] Code the service following [this Spark tutorial](http://sparkjava.com/tutorials/twitter-clone)
- [ ] Create a Pull Request to https://github.com/hexagonkt/twitter_clone from your project
- [ ] As an optional addition, you can add [Codecov](https://codecov.io) test coverage report inside the Travis CI pipeline

For reference, you can check this other example: https://github.com/hexagonkt/real_world. And of course, I will help you with it if you ask me (as I already did developments like this).

Have fun, and happy coding!

**Comment by augustohdias** [comment]
I'd like to take this! #hacktoberfest

**Comment by jaguililla** [comment]
I just assigned the task to you. Just let me know if you need anything!

**Comment by jaguililla** [comment]
Hello, I'm just reviewing the Hacktoberfest issues still open. If you didn't finish the task, but still you want to commit what you've done. Come on, any help will be welcomed and I can finish the remaining part of the task :slightly_smiling_face: 

Next week I will proceed to update this task status and assignees. Thanks!

**Comment by BikramjeetSingh** [comment]
Hello! I'd like to take this issue up.

**Comment by jaguililla** [comment]
Sure! Thank you for your contribution :)

Do not hesitate to contact me if you need anything. You can do so in this issue's comments or by Slack.

Happy coding!

**Comment by BikramjeetSingh** [comment]
@jaguililla I can't seem to be able to access the project's Slack channel. Do I need an invite?

**Comment by jaguililla** [comment]
Yes, you have to request an invitation to JetBrains. You can do so [here](http://slack.kotlinlang.org/?_ga=2.49986662.1103721712.1584300803-1878487877.1578514032). They usually accept it very quickly.

**Comment by aneeshdua** [comment]
@jaguililla can I work on this?

**Comment by jaguililla** [comment]
Glad to ear that @aneeshdua ! However @BikramjeetSingh is already working on this example project.

You can contact him to share the development, or you can pick the #171 which is also a nice example to develop :)
