### ISSUE TITLE
Add `buildSrc` tests

### ISSUE THREAD

**Issue by jaguililla** [hexagonkt/hexagon#216]
The `hexagon_site` module has a slightly bigger build logic that the others. This logic involves:

* Replacing variables in Markdown pages
* Replacing placeholders with code snippets (located in tests to be sure they work properly)
* Checking that `readme.md` code is the same that the one checked by tests.

This code is (partially) taken to `buildSrc` to code it in Kotlin instead in Groovy. However this code is not unit tested yet.

This task's goal is to cover that code with tests.

If the code's purpose is not clear, you can ask me, and I'll gladly answer your questions :)

**Comment by 0001vrn** [comment]
Hi @jaguililla 
I want to contribute to this issue. I am getting started. Let's connect for this so that we both can have a clear understanding of what should be the outcome of this issue when resolved.
Thanks
Varun

**Comment by jaguililla** [comment]
Hello @0001vrn Thanks for your contribution (I just checked the PR) I'm missing some corner cases (check the PR comment) but if you want, I can merge the PR and let you complete the scenarios in a different PR if you want. Thank you very much!

**Comment by 0001vrn** [comment]
Hi @jaguililla 
It is my pleasure to be able to contribute to the repo. Sure, going forward, would be discussing scenarios in the aforementioned slack channel. I am also a member of it now. Thanks to you 🙏

You're welcome! 😉
