### ISSUE TITLE
Create a base Docker image

### ISSUE THREAD

**Issue by jaguililla** [hexagonkt/hexagon#223]
Create image with common files to require only the application JAR.

To complete this task. It is necessary to:

* [ ] Create a module called `hexagon_docker`
* [ ] Do the build so it creates an empty application with all the toolkit dependencies
* [ ] Create a Dockerfile that packages all JARs (dependencies) and scripts that can be reused in other applications
* [ ] Build the image in the build process
* [ ] Publish the image to https://hub.docker.com when the release is made

If any point requires further details. Please let me know in the comments!

**Comment by EvertonSA** [comment]
i would like to take this task

**Comment by jaguililla** [comment]
Hello, I'm just reviewing the Hacktoberfest issues still open. If you didn't finish the task, but still you want to commit what you've done. Come on, any help will be welcomed and I can finish the remaining part of the task :slightly_smiling_face: 

Next week I will proceed to update this task status and assignees. Thanks!

**Comment by jaguililla** [comment]
Application packages are below 20 MB Having an image with all dependencies inside doesn't bring a big improvement at the moment. Discarding this task by now
