### ISSUE TITLE
Port Gradle build scripts to Kotlin

### ISSUE THREAD

**Issue by jaguililla** [hexagonkt/hexagon#224]
Build logic is written in Groovy (all `*.gradle` files).

The goal of this task is to port those build scripts to Gradle kotlin DSL (`*.gradle.kts`).

This task can be completed with different PRs (one by each `.gradle` file migrated).

EDIT: The missing scripts right now are:

* Helper scripts located inside `gradle` directory. These ones should be ported in a `kts` folder before deleting the Groovy ones.

**Comment by SilvioMachado** [comment]
May i work on this issue too?

**Comment by jaguililla** [comment]
Sure @SilvioMachado , just talk to @norangebit to split the build files. A good place to do this could be the Hexagon's Slack channel: https://kotlinlang.slack.com/messages/hexagon

You can request access to JetBrains (they usually grant it fast) here: http://slack.kotlinlang.org/?_ga=2.249896774.1758923605.1570641033-247235827.1559760269

**Comment by jaguililla** [comment]
@norangebit Add a comment here to add you to this task's assignees list :)

**Comment by norangebit** [comment]
Yep, I'm in.

**Comment by pavi2410** [comment]
I would also like to take this up.

**Comment by pavi2410** [comment]
I am working on improving https://github.com/bernaferrari/GradleKotlinConverter so that most of the `build.gradle` files can be converted to `build.gradle.kts` without much additional changes. So, please bear with me for a few days :)

**Comment by jaguililla** [comment]
Hello, I'm just reviewing the Hacktoberfest issues still open. If you didn't finish the task, but still you want to commit what you've done. Come on, any help will be welcomed and I can finish the remaining part of the task :slightly_smiling_face: 

Next week I will proceed to update this task status and assignees. Thanks!

**Comment by pavi2410** [comment]
I am quite busy with my end semester exams which wilp be over by the next
week. I think I shall be able to contribute.

**Comment by jaguililla** [comment]
No problem, I just wanted to know if you would like to continue working on this... I appreciate your help, but in Open Source there's no strings attached... Good luck with your exams! :)

**Comment by jaguililla** [comment]
All project's build scripts have been ported except the `gradle/*.gradle` helpers used in other projects.

They won't be ported as the way to go is precompiled plugins: https://docs.gradle.org/current/userguide/custom_plugins.html#sec:precompiled_plugins

Eventually they could be ported to precompiled plugins, but they'll need to be published.
