### ISSUE TITLE
Implement Metrics support

### ISSUE THREAD

**Issue by jaguililla** [hexagonkt/hexagon#260]
**NOTE** This task is not yet fully detailed, if you claim it, I will add details on demand :)

Check:

* https://opentelemetry.io
* https://metrics.dropwizard.io
* https://micrometer.io/

**Comment by eboliveira** [comment]
Hi @jaguililla,

I would like to contribute to this.

**Comment by jaguililla** [comment]
This can be implemented as a filter outside the toolkit.
