### ISSUE TITLE
Add Java 11 HTTP Client adapter

### ISSUE THREAD

**Issue by jaguililla** [hexagonkt/hexagon#270]
Implement the `port_http_client` using the JDK11 internal HTTP client.

The Async HTTP Client adapter (`http_client_ahc`) can be checked as a reference.

The module should pass the test suite implemented in the Port (again, as a reference you can check `http_client_ahc` tests).

**Comment by Terril** [comment]
Hi,

I would like to contribute to this.

**Comment by jaguililla** [comment]
Sure! go ahead... Just ask me anything you need :)

**Comment by jaguililla** [comment]
Hi @Terril would you like to continue working on this task? If you can't give it time... I understand :) just let me know (in order to move it to the backlog or work on it)... Thanks!

**Comment by Terril** [comment]
@jaguililla sorry for delaying it. Will be creating a PR for this soon
