### ISSUE TITLE
Enforce signed dependencies in Gradle

### ISSUE THREAD

**Issue by jaguililla** [hexagonkt/hexagon#275]
Gradle 6.2 allow forcing to use only signed dependencies. Do it for the same of security.

**Comment by donky106** [comment]
Hi, I would like to work on this issue

**Comment by jaguililla** [comment]
Thank you for contributing! I just assigned it to you and move to the 'Working' column, if you need any help, do not hesitate to ask :)

If you check the site you'll find the project Slack Channel (it requires JetBrains request to join, but they do that really fast). You can contact me there or comment this issue. However, Slack would be faster.

**Comment by donky106** [comment]
Hi,

first I created a config file verification-metadata.xml

1) The hash values were missing for 55 artifacts. The Gradle message was "Checksums are missing from verification metadata".

So I run Gradle to create the SHA-512 hash value, i.e. checksums

./gradlew -x test --write-verification-metadata sha512 help

The checksums are in the config file now

<artifact name="backport-util-concurrent-3.1.jar">
<sha512 value="5f881cb5fc18df80f574ab3af261ef4a45a628794b40c3ffd896af98b9fbbf06ad65ac41e0688fefc9769901bc84a0eff866c77bf07af467a26c811003845f62" origin="Generated by Gradle"/>
</artifact>

2) After I turned on the signature verification, 53 artifacts failed verification with 3 types of errors: 

a) Artifact was signed with key xxx but this key is not in your trusted key list

b) Key xxx (not found) couldn't be found in any key server so verification couldn't be performed

c) Artifact was signed with key xxx but signature didn't match

I run ./gradlew -x test --write-verification-metadata pgp,sha512 help

this cmd will 

1) automatically add the trusted keys as soon as verification passes

2) automatically add ignored keys for keys which couldn’t be downloaded from public key servers

3) automatically generate checksums for artifacts without signatures or ignored keys

So <ignored-keys> and <trusted-keys> entries have appeared in the config file.

After all I have exported all the keys to the verification-keyring.gpg

./gradlew -x test --write-verification-metadata pgp,sha256 --export-keys

Do you want to keep it as it is or should we do better, i.e. search for hash values for each artifact manually and so on?

**Comment by donky106** [comment]
many artifacts have no hash values provided. For these ones Gradle generates the hashes for the first use

**Comment by jaguililla** [comment]
Hi, sorry for the late reply, and thank you for your great work and explanation!

I think that you can commit those settings as you have them. Further improvements can be done later if required.

So, if you want, you can file a PR and we can discuss the changes there. Thanks!
