### ISSUE TITLE
Add XML serialization format

### ISSUE THREAD

**Issue by jaguililla** [hexagonkt/hexagon#280]
As Jackson supports the XML datatype: https://github.com/FasterXML/jackson-dataformat-xml , the scope of this task would be to create a Content Format module to support it.

As a reference you can check the YAML Content format implementation in the `serialization_yaml` module.

**Comment by hadv** [comment]
I'd love to do this task

**Comment by jaguililla** [comment]
Hello! and thanks for the interest in the project. I'll assign it to you and put it in the 'Working' column. Please, do not hesitate to contact me if the issue is missing some information.

You can also contact me on Kotlin's Slack (jaguililla). You can request an invitation here: https://kotlinlang.org/community (they are usually quick in granting the access).

Thanks again and we'll be in touch!

**Comment by hadv** [comment]
Hi @jaguililla 

I add jackson-dataformat-xml into the dependencies but I need to update the `verification-metadata.xml` file to add some related dependencies libs' trusted key also. Can you guide me the detail steps to do this?

Thank you!

**Comment by jaguililla** [comment]
You can check the details on the `contributing.md` file.

But for this case: you can copy & paste another Jackson entry on the `verification-metadata.xml` file (on the `<trusted-keys>` section) changing the name to `jackson-dataformat-xml`. I.e.:

`<trusted-key id="6214760097dc5cfad0175ac2c9fbaa83a8753994" group="com\.fasterxml\.jackson\..*" name="jackson-dataformat-xml" regex="true"/>`

**Comment by hadv** [comment]
Yes, I already read it but I don't know where to get the trusted-key id of other dependencies, due to xml need two other below libs

```
2 artifacts failed verification:
  - stax2-api-4.2.1.jar (org.codehaus.woodstox:stax2-api:4.2.1) from repository BintrayJCenter
  - woodstox-core-6.2.1.jar (com.fasterxml.woodstox:woodstox-core:6.2.1) from repository BintrayJCenter
```

**Comment by jaguililla** [comment]
The build fails with a link to a HTML report. Inside you can find the keys used to sign those dependencies.

You can verify the fingerprint using a public key server (I guess there are instructions in `contributing.md`, otherwise, tell me). 

After that you can add the fingerprint to the dependency the same way you did with the `jackson-dataformat-xml` 🙂

**Comment by jaguililla** [comment]
Hi @hadv would you like to continue working on this task? If you can't give it time... I understand :) just let me know (in order to move it to the backlog or work on it)... Thanks!

**Comment by jaguililla** [comment]
Pending documentation in the site
