### ISSUE TITLE
Upgrade MkDocs Material

### ISSUE THREAD

**Issue by jaguililla** [hexagonkt/hexagon#292]
Upgrade to MkDocs Material 5. To do so, you can check the theme's documentation: https://squidfunk.github.io/mkdocs-material/upgrading/

We can take advantage of the new version to add Dev.to link as blog/news using this icon: https://fontawesome.com/icons/dev?style=brands

Use also a Web app manifest and service worker may be another improvement.

**Comment by SalmonKing72** [comment]
I'd like to help with this.

**Comment by jaguililla** [comment]
Sure! It's all yours... Let me know if you need anything from my side :)

**Comment by SalmonKing72** [comment]
@jaguililla do you require all 3 items as acceptance or is the service worker optional?

**Comment by jaguililla** [comment]
The worker is a nice to have... you can leave it aside and I will create another issue only for that

**Comment by SalmonKing72** [comment]
@jaguililla sounds good. Where are you looking to use the dev.to icon as a link? Is this in the community nav or perhaps as part of the social links in the footer?

**Comment by jaguililla** [comment]
Use the icon only in the footer, please :)

**Comment by SalmonKing72** [comment]
I found a small issue with the mongoDB tests where the TimeZone doesn't seem to be considered which was causing assertions to fail for me since the day is off by 1 in some of the cases. I've added this to fix. Let me know if it's okay to include in this PR or if you want a separate issue and PR.

```
companion object {
        @BeforeAll
        @JvmStatic
        fun resetTimeZone() {
            TimeZone.setDefault(TimeZone.getTimeZone("UTC"))
        }
    }
```

**Comment by jaguililla** [comment]
That's a nice catch! Thank you, I would prefer to have it as a separate PR if you don't mind :)

**Comment by SalmonKing72** [comment]
@jaguililla sounds good. would you like a separate issue created as well? I'll go ahead and do that if you want to have the separate PR linked to it.

**Comment by jaguililla** [comment]
No need for the issue, adding the description in the PR is fine. If you are participating in Hacktoberfest and it doesn't count a PR without an issue just let me know... but I guess it is no problem...  :) Thank you!

**Comment by SalmonKing72** [comment]
> No need for the issue, adding the description in the PR is fine. If you are participating in Hacktoberfest and it doesn't count a PR without an issue just let me know... but I guess it is no problem... :) Thank you!

@jaguililla Thanks for the help! I have this PR, https://github.com/hexagonkt/hexagon/pull/335 ready. If you wouldn't mind putting the `hacktoberfest-accepted` label on that, that would be greatly appreciated. Once that's approved and merged into `develop`. I'll wrap up the work for #292 and submit a separate PR.

**Comment by jaguililla** [comment]
Done!
