### ISSUE TITLE
Review Templates Port

### ISSUE THREAD

**Issue by jaguililla** [hexagonkt/hexagon#310]
* Make the necessary changes to support streams. Allow templates to be loaded from any input stream (not only resources).
* Allow to use it standalone (for CLI or GUI applications). This should be done by making the data loading (from resources) optional.
* Make proper documentation and link it in the main site section: Explain how to register one or more template engines and how to render templates (using context data).
* Support configuration:
  * Register Template Adapters to templates patterns. I.e.: `pebble/**/*.html` -> PebbleAdapter
  * Set up automatic context loading from resources
  * I18N for resources

**Comment by jdornieden** [comment]
Very interesting project! I'd like to work on this one. However, I might need some more information on how you would like to have the configuration of multiple adapters.

**Comment by jaguililla** [comment]
Sure! I've assigned this issue to you and moved to the 'Working' column.

To register different adapters, you can create a method in `TemplateManager`. I.e.: `fun register(pattern: String, adapter: TemplatePort)`. To discuss how this would play with the dependency injection and different implementation strategies, you can chat with me in Kotlin's Slack channel (you can join it here: https://kotlinlang.org/community).

Thanks for supporting this project!
