### ISSUE TITLE
Parse query and form parameters into type

### ISSUE THREAD

**Issue by jaguililla** [hexagonkt/hexagon#311]
Create a method to parse all received parameters (forms, query, path) inside a class with the desired types, structure and checks.

The method would be something like: `fun <T: Any> Request.allParameters(type: KClass<T>): T` this method will:
1. gather all request's parameters (form, path and query ones)
2. put them in a map (taking care of the parameters that have a list of values)
3. convert the map in the supplied type
4. if conversion fails, halt the request with a 400 error

I.e. For a received request with:
* Path param: teamId: team
* Query param: userId: [ usr1, usr2, usr3 ]
* Parameter parsing type:
```kotlin
data class FilterUsers(val teamId: String, val userId: List<String>) {
  init {
    require(teamId.isNotBlank())
  }
}
```
Calling `request.allParameters(FilterUsers::class)` would return a `FilterUsers` instance with the parameters mapped.

For later revisions the error handling will be revisited to provide more details if the method fails to map the parameters to the desired type.

**Comment by AnoojPoozhikuth** [comment]
Hello @jaguililla , I can claim this if that is ok.  Could you please provide me with more details?

**Comment by jaguililla** [comment]
Done! and sorry for the delay.

**Comment by AnoojPoozhikuth** [comment]
Got stuck with work a bit :) 

Trying to clarify few things @jaguililla 
1. "Request" mentioned here is this class - com.hexagonkt.http.client.Request  - right ?
2. I can create an extension method (maybe inside the same file or in a new file, please let me know if you have any suggestion) which as you mentioned above will do mapping of all type of request params 
3. Method will extract all fields and form a map containing all these key-value pairs accordingly  ( I assume the same key will not repeat in query and form or inform and path etc
4. If the mapping fails / if there is nothing to map, I shall handle the exception and return a null object of the given class (or an optional)

**Comment by jaguililla** [comment]
Sorry for the late reply... I added a comment in the #333 PR Thanks!

However, regarding your points:
1. It was intended for parsing parameters to a type in the server (however, it is easy to move there)
2. Extension method is fine
3. Yes, assume keys won't be repeated, it could be a nice addition to log a warning if that happen. But it is ok that way
4. Returning null as you did is perfectly fine, maybe at a later iteration a method like `forceParse` can be added to return the instance or raise an exception.
5. Query params may contain multiple values, in that case. If the list contains only one value, convert it to a single option... Parameters with a list of values mapped to a class with a single value will fail (and that is good).
6. there is a `queryParameters` map in the server request.

Thank you for your insights, and sorry for taking that much time in replying.

**Comment by AnoojPoozhikuth** [comment]
Ok, so the task has to be based on _**com.hexagonkt.http.server.Request**_  , right ?   which is extended by _internal class Request_

Let me change my PR accordingly
