### ISSUE TITLE
Build mock servers from OpenAPI specs for testing

### ISSUE THREAD

**Issue by jaguililla** [hexagonkt/hexagon#312]
The purpose of this task is to create a function that returns a `Server` from the information of an [OpenAPI YAML spec](https://swagger.io/specification).

The YAML input should be a URL to let the user choose the specs source (it could be a web address, a local file or a classpath resource).

The server will take all its data from the spec (I.e.: base path), and the request and response of the routes will be determined by the routes' examples and schemas.

The mocked services' handlers will check the input (body, parameters, etc.) against the inputs declared in the OpenAPI spec, and return a response taken from the examples of the spec (the actual response among all examples can be selected from a custom header. I.e.: `X-Mock-Response-Example`).

the server router could be overwritten to mock responses specific for a test. This could be tricky and it would be OK to leave this for future improvement.

This code will be used to simulate other services in microservices' integration tests. So the port should be supplied along the Spec URL (allowing it to be `'0'` for a dynamic port).

To parse specs the [Swagger Java Core library](https://github.com/swagger-api/swagger-core) can be used, easing the process of processing the file.

This functionality can be developed inside the `port_http_server` module, at the test sourceset and the `test` package. Being there it could be possible to add it as a test dependency with this coordinates: `com.hexagonkt:port_http_server:VERSION:test`

In the future in could be handy to move it to another module as a standalone service able to load a set of OpenAPI specs to serve them outside integration tests.

**Comment by BikramjeetSingh** [comment]
I would like to give this task a try.

**Comment by jaguililla** [comment]
Assigned... Thank you!

**Comment by BikramjeetSingh** [comment]
Hi, so the approach I thought of taking is as follows:

I'll make use of the [swagger-parser](https://github.com/swagger-api/swagger-parser) library to parse the spec file. I'll create a nested mapping where the key will be a particular route and the value will be _another_ map, whose key will be an HTTP method (GET, POST, PUT, etc) and value will be the mock response. Basically, it will look like this: `HashMap<String, HashMap<String, String>>` where the key of the outer map is the path, the key of the inner map is the HTTP method and the value of the inner map is the mock response. I hope this explanation was clear, please let me know if it isn't.

Then, I'll create a `Server` with a `Router` with a single route, `any("*")`. This way, any request that is sent to the mock server will be captured by this route. Within the route body, I'll check what the actual method and path of the request is, compare it with the previously created mapping and return the corresponsing mock response. For the comparison I guess we can make use of the same code that Hexagon uses internally to resolve a route.

I have a question: in an actual server, a single route can obviously return multiple statuses (200, 400, 404, etc). I'm not sure how we can implement this mock server to be able to return more than one type of status. Or, perhaps, the mock server can only return mocks of successful responses?

Please let me know what your thoughts are.

**Comment by jaguililla** [comment]
> Hi, so the approach I thought of taking is as follows:

Hi! I'm replying over your message.

> I'll make use of the swagger-parser library to parse the spec file. I'll create a nested mapping where the key will be a particular route and the value will be another map, whose key will be an HTTP method (GET, POST, PUT, etc) and value will be the mock response. Basically, it will look like this: HashMap<String, HashMap<String, String>> where the key of the outer map is the path, the key of the inner map is the HTTP method and the value of the inner map is the mock response. I hope this explanation was clear, please let me know if it isn't.

Ok, though this approach is valid, you could also do it by parsing the Swagger spec and getting something like (in pseudocode):

```kotlin
val swaggerRoutes: List<SwaggerRoute> = SwaggerParser.parse(URL("http://integration_server/latest_build/spec.yml"))
```

Then you could do something like:

```kotlin
val router = Router {
    swaggerRoutes.forEach { sr ->
        when (sr.method) {
             GET -> get(sr.path) { handle(sr) }
             POST -> get(sr.path) { handle(sr) }
             // ...
             else -> error(":O")
        }
    }
}
```

And finally mount that router inside a server. You could put that code into a method i.e.: `createRouter(URL)` and mount many specs into one server, or map each of them to its own server :)

Please, bear in mind that I'm speaking based on nothing (I don't know if the Swagger parser returns the information like that). Be my guest to tell me what you think about this approach.

> Then, I'll create a Server with a Router with a single route, any("*"). This way, any request that is sent to the mock server will be captured by this route. Within the route body, I'll check what the actual method and path of the request is, compare it with the previously created mapping and return the corresponsing mock response. For the comparison I guess we can make use of the same code that Hexagon uses internally to resolve a route.

It is better if you are able to do it without relying on internal code... that would imply copy paste, double maintenance and not being able to take advantage of improvements done in the routing later. Does this makes sense?

> I have a question: in an actual server, a single route can obviously return multiple statuses (200, 400, 404, etc). I'm not sure how we can implement this mock server to be able to return more than one type of status. Or, perhaps, the mock server can only return mocks of successful responses?

Ok, this is the second part of the problem... Following with the previous snippet, we could focus on the `handle` method to tackle this problem:

```kotlin
fun Call.handle(sr: SwaggerRoute) {
    // Here would go the request's body check (based on Swaggers schema)
    // You can skip it... this could be very hard, and could be another task on its own

    val ex: String = sr.examples.get(request.headers["X-Mock-example"])
       ?: sr.examples.first()

    send(ex.status, ex.body, ex.contentType)
}
```

> Please let me know what your thoughts are.

You did a pretty good analysis of the problem... I differ on some aspects, but the overall picture looks good to me. Thank you for working on this feature, and keep up the good work!

**Comment by BikramjeetSingh** [comment]
Hi,

Actually, I think your approach of iterating over the Swagger routes is better. Thanks for the suggestions. I checked, and the Swagger parser does return information in a suitable format, so this approach should work fine.

> It is better if you are able to do it without relying on internal code... that would imply copy paste, double maintenance and not being able to take advantage of improvements done in the routing later. Does this makes sense?

You're right, that makes sense. I didn't think of that. Although I think with the new approach of creating the Router that you suggested, this problem solves itself. So we needn't worry about it as of now.

> You did a pretty good analysis of the problem... I differ on some aspects, but the overall picture looks good to me. Thank you for working on this feature, and keep up the good work!

Thank you for the encouraging words!

**Comment by jaguililla** [comment]
Thanks to you! just ask me anything you want... I'll be glad to help!
