### ISSUE TITLE
Routing handling with filters

### ISSUE THREAD

**Issue by maiph** [hexagonkt/hexagon#318]
Hello there 😃 
Found it while looking for open source projects to contribute to and this is something I was interested in and that I could learn from.

I would like to know what was the design decision on the request routing implementation.
It seems like you register a `ServletFilter` to the `ServletContextHandler` and call the route callback inside the `doFilter`.
https://github.com/hexagonkt/hexagon/blob/59d77521d41c507fa7b179c39984b74c058b8c5e/http_server_servlet/src/main/kotlin/ServletFilter.kt#L143
and then 
https://github.com/hexagonkt/hexagon/blob/59d77521d41c507fa7b179c39984b74c058b8c5e/http_server_servlet/src/main/kotlin/ServletFilter.kt#L98

What I noticed is that you are not following the expected behaviour of the [Filter behaviour](https://docs.oracle.com/cd/B32110_01/web.1013/b28959/filters.htm#BCFIEDGB) by not calling the `doFilter` of the chain.

Just wanted to understand if this was done for a specific reason or just as a _"cost cut"_ measure and take advantage of how the servlet context handler handles requests.
I also think there is something already in jetty that does some kind of routing based on the request path.

Loving the project and learning a lot from it ❤️

**Comment by maiph** [comment]
Later I saw that the servlet path definition is not very flexible and understand a bit more about it.

Also took a look at the docs from Jetty and saw that they don't event recommend using servlets if we can't take any advantage from them as they will only bring an unnecessary overhead. What they recommend is that the request handling is all done with Handlers. The idea I got from that would be to have a RouteHandler that would see what route the request is supposed to be sent and call the before, callback, and after for the route.
This approach allows a better separation of concernes (with something like: BeforeRouteHandler, RouteCallbackHandler, AfterRouteHandler) and allows to chain all the Handlers in succession or wrapping other handlers.

**Comment by jaguililla** [comment]
You are right, using Jetty at a lower level improves the performance over using Servlets.

The reason behind this decision is to take advantage of the Servlet implementation made for Web applications (WAR files) to cut development time.

In the future, the best option would be to provide another Adapter using Jetty "low" level library (or other Adapter for, let's say undertow.io). And take advantage of the Port/Adapter architecture.

That's the goal, but before providing more adapters, the next milestone is to cover minimal functionality (parts missing are Auth and WebSockets).

Thanks again for your thoughts!
