### ISSUE TITLE
Upgrade Dokka Gradle plugin

### ISSUE THREAD

**Issue by jaguililla** [hexagonkt/hexagon#326]
Dokka is used to generate a BIG part of the site.

Some post processing of Dokka generated Markdown is done in Gradle scripts.

Te goal of this task is to use the latest Dokka plugin (1.4.10 alpha) and in the process check if some logic inside Gradle can be moved to Dokka plugins.

As a reference, you can check: https://blog.jetbrains.com/kotlin/2020/09/dokka-alpha-for-kotlin-1-4

**Comment by ThinkHattke** [comment]
Can I work on this @jaguililla ?

**Comment by jaguililla** [comment]
Sure! I just assigned the task to you... If you need anything, just contact me!

**Comment by ThinkHattke** [comment]
Sure @jaguililla , will reach out if I need any help. Thank you :)

**Comment by Megamiun** [comment]
Hello, was there ay news about this task?

**Comment by jaguililla** [comment]
Hi @ThinkHattke would you like to continue working on this task? If you can't give it time... I understand :) just let me know (in order to move it to the backlog or work on it)... Thanks!
