### ISSUE TITLE
Error parsing query parameters

### ISSUE THREAD

**Issue by jaguililla** [hexagonkt/hexagon#328]
If a query parameter is defined with an empty value (I.e.: `?status=`) a 500 error is returned.

In that scenario we should assume it is a single element list with an empty string (as if you pass `?status`).

**Comment by pedro-cze** [comment]
Hello, @jaguililla I'd like to take this one, unless it's already taken.

**Comment by BikramjeetSingh** [comment]
Sure, @pedro-cze feel free to pick this up.

**Comment by pedro-cze** [comment]
Hello @jaguililla I'd like to push the fix, but I am unable to do it due to insufficient privileges. I get the `403` on `git push` (tried ssh & github credentials). Is there something I am missing? Thanks.

```
ERROR: Permission to hexagonkt/hexagon.git denied to pedro-cze.
fatal: Could not read from remote repository.
```

**Comment by jaguililla** [comment]
Hi... and sorry for the late reply.

Contributions to the project are made via Pull Request (PR). To do so, first you have to create a fork of the project and commit your changes there. After that, you can file a PR from your source to the origin project.

As I guess you already cloned `hexagonkt/hexagon`, you have to create the fork (which would end up being something like `pedro-cze/hexagon`) and in your local workspace execute `git remote set-url origin <url of your fork>`. After this, you can push your changes there, and lastly create the PR.

You can check more detail about this process on this GitHub guide (https://opensource.guide/how-to-contribute/#opening-a-pull-request).

Thank you for working on this issue! And if you have troubles doing this, just let me know :)

**Comment by pedro-cze** [comment]
Great, thank you too. I created the PR. I sincerelly hope that there is eveything formally and functionally ok with it. Please give me a word if there is still something wrong/missing. Thanks.

**Comment by jaguililla** [comment]
Merged... Thanks for your contribution!
