### ISSUE TITLE
Upgrade to MkDocs Material 6.x

### ISSUE THREAD

**Issue by jaguililla** [hexagonkt/hexagon#339]
Upgrade to MkDocs Material 6. To do so, you can check the theme's documentation: https://squidfunk.github.io/mkdocs-material/upgrading/

**Comment by Debadri3** [comment]
Can I work on this issue?

**Comment by jaguililla** [comment]
Thanks for your interest @Debadri3 :) this issue was proposed by @SalmonKing72 at the PR #338 

Take a look at the rest of the backlog if you want, if some other task seems appealing to you, I can give you more details :)

**Comment by SalmonKing72** [comment]
@Debadri3 feel free to take this if you've made progress already. I'll pivot to something else in the backlog.

**Comment by SalmonKing72** [comment]
@jaguililla caught up on the commentary around this. If you want to assign this to me. I can keep running w/ it.

**Comment by jaguililla** [comment]
Done!

**Comment by jaguililla** [comment]
Hi @SalmonKing72 regarding documentation, I made some small adjustments in the latest PR (just to let you know).

However, with the most recent versions of MkDocs Material it seems that the search box and the tabbed code snippets stopped working (I were not able to make them work again :( ).

If you are able to fix those issues that would be wonderful. If you cannot, you can stop working on this task as I would consider changing to a different document generator (it is very time consuming to keep MkDocs working correctly) :(

**Comment by SalmonKing72** [comment]
@jaguililla sounds good. I can look at it more. Did those features stop working with version 5.x or 6.x?

**Comment by jaguililla** [comment]
Yes... they were working on 4.x and stopped with 5.x (they didn't work on 6.x neither). I dig a little bit, and it seems to be a problem picking the `lang` config of the `search` plugin (I set it up, however, it should pick 'en' by default). I cannot make it work, maybe is a a MkDocs or MkDocs Material bug.

And the tabbed code snippets syntax changed. The problem is that Dokka generates the Markdown in an incompatible way with Pygments (used by MkDocs).

If you are willing to give it a second guess... I appreciate it!

**Comment by jaguililla** [comment]
I found the problems, they are fixed in `develop`, the remaining issue in this task is to migrate to 6.x version :)

**Comment by SalmonKing72** [comment]
Sounds great. I pulled the changes last night. I should have some time over the next few days to dig into this more. Sorry for the radio silence... I've been busy with other personal matters. Thanks for the update!
