### ISSUE TITLE
Add compression support

### ISSUE THREAD

**Issue by jaguililla** [hexagonkt/hexagon#34]
Implement compression support in `port_http_server` and `port_http_client`.

The goal would be to add a configuration parameter in the `(Server|Client)Settings` classes and force the compression headers to be sent accordingly.

The proper encoding and sending/receiving bodies must be checked by tests in the Ports' tests suites (the test classes used to validate adapters modules).

As a reference, you can check the fabulous MDN documentation regarding the subject:

* https://developer.mozilla.org/en-US/docs/Web/HTTP/Compression
* https://developer.mozilla.org/es/docs/Web/HTTP/Headers/Content-Encoding

**Comment by sumitkp18** [comment]
Hi @jaguililla ,
I have read the given reference docs of MDN on encoding and want to try to work on this task.
As per my understanding the Client needs to send the "Accept-Encoding" in headers of ClientSettings instance which needs to be handled accordingly by the Server for compression and sending back the proper headers through ServerSettings.
Could you please give some more context on the requirement?

**Comment by jaguililla** [comment]
Ok, it is exactly the way you described it. Note that you can pass the `Accept-Encoding` header in a request basis (not required to pass it on the ClientSettings parameters).

The server should react in the case the header is passed compressing the output and sending the `Content-Encoding` header (not sure it is the exact name) back.

Note that for the Server adapters (I.e.: Jetty) this could be already the behaviour and no change is required on the servers.

So:

1. A test is required to verify that under proper request, the response is compressed
2. Update ClientSettings with a `encoding` field which will add the `Accept-Encoding` to all of that client's requests
2. If the test pass for all the adapters, that is all :)
4. If not, the adapters will have to be updated to control this header and compress the response according to their APIs.

If something is not clear (or you see is wrong or doesn't fit well), please, question me as long as you need to :)

In the meantime, I will assign this issue to you and move it to the working column

**Comment by sumitkp18** [comment]
Thanks for the explanation @jaguililla .

**Comment by sumitkp18** [comment]
How can we check whether the compression is handled on the server side? like as you mentioned it is handled for JettyServerAdapter.

I tried to add the encoding parameter to ClientSettings and handled it in send() method of Client by adding a parameter "Accept-Encoding: gzip" to the request headers.

I tested it in one of the tests in ClientTest, while debugging the request object had the encoding param in the headers but I didn't receive a compressed output an neither did I receive any "Content-Encoding" parameter in the response headers.

**Comment by jaguililla** [comment]
Ok, if you didn't get the header in the response, probably it is not compressed. So you could research about implementing compression using Jetty (for this particular adapter). I searched a little bit and I found this:

* https://stackoverflow.com/questions/24521426/setup-jetty-gziphandler-programmatically
* https://www.eclipse.org/jetty/documentation/current/gzip-filter.html

I don't know if that could make it... but I hope it could be a starting point :)

**Comment by sumitkp18** [comment]
Thank you so much @jaguililla for clarifying.
I will look into the resources and do some further research on it.

**Comment by sumitkp18** [comment]
@jaguililla 
I was again trying to debug to understand how to add compression on server side, the response I am getting for Jetty adapter contains Content-Encoding: chunked.
And also as per documentation it seems jetty already handles gzip compression, but I am not sure why I am not getting a compressed response when provide with proper headers for Accept-Encoding.

**Comment by jaguililla** [comment]
I would need to look into this with more detail... give some days to check it out :)

**Comment by jaguililla** [comment]
Hello, and sorry for the late reply. While I was changing the ServerPort interface I found out about Jetty GZIP support, so it is already implemented in the 1.3.6 version. Sorry for the delay on the communications :(

I will close this ticket as it is already implemented. Thanks!
