### ISSUE TITLE
WebSockets support

### ISSUE THREAD

**Issue by jaguililla** [hexagonkt/hexagon#35]
When completed, create an example project like this one: http://sparkjava.com/tutorials/websocket-chat to show the feature.

Check Javalin implementation: https://javalin.io/documentation#websockets

This task is composed of two big areas:

## 1. Define the DSL to handle Websockets 
The DSL will implement methods to add routes of WS type inside the router. I.e.:
       
```kotlin
Router {
    webSocket("/path") {
        onConnect {
            send("Message back")
        }
        onError {
            send("Message back")
        }
        onMessage {
            send("Message back")
        }
        onClose {
            send("Message back")
        }
    }
}
```

All callbacks will have a `context` to send/receive data to the client. This context will hold 
methods to get/set attributes, headers, etc.

## 2. Implement the routes on adapters
The above step will add a list of routes to the router. On the adapters implementations, these 
routes will be converted into the adapter's library format in the `fun startup(server: Server)`
method.

You can check the implementation of this method on the
`http_server_jetty/src/main/kotlin/JettyServletAdapter.kt` file, but the actual logic is also on the
`http_server_servlet/src/main/kotlin/ServletFilter.kt` file.

**Comment by sumitkp18** [comment]
Hi @jaguililla ,
I have read the spark java implementation for the websocket example and would like to take this task.

**Comment by jaguililla** [comment]
You have to know that this feature is still in the 'design' phase and it would require more investigation to define a final API.

It is not a quick one, but if you don't mind taking the time, we can discuss the API, implementation, tests, etc.

I was looking into the Web Socket implementation of javalin.io (https://javalin.io/documentation#websockets) that I find more clear than Spark's one (and also without requiring annotations). And the Jooby one: https://jooby.io/#web-sockets

This is a long shot and if you just want to achieve the Hacktoberfest challenge, this is not for you ;) However, if you are willing to implement this in the long term... welcome aboard!

**Comment by sumitkp18** [comment]
Thanks for providing the context @jaguililla .
I am interested in learning web sockets. Will be glad to work on it for long term. Will need some guidance in case I get stuck.
Will go through the javalin and jooby implementations too and also study more on websockets. 
Thanks for encouraging!

**Comment by BikramjeetSingh** [comment]
I am almost finished finalizing the DSL. I thought it would be a good idea to share the tentative API available to end-users of the library. Wherever possible I tried to keep the property names similar to the corresponding properties in the `Call.kt` class.

**Properties:**
```
path: String (the URL path to the WebSocket endpoint, eg "/v1/ws")
pathParameters: Map<String, String> (read-only)
queryParameters: Map<String, String> (read-only)
queryParametersValues: Map<String, List<String>> (read-only)
headers: Map<String, String> (read-only)
cookies: Map<String, Cookie> (read-only)
```

**Methods:**
```
send(content: String) (support for binary and serialized data to be added later)
close(statusCode: Int, reason: String)
```

**Example usage:**
```kt
webSocket("/samplewebsocket") {
    onConnect {
        send("Hello WebSockets!")
    }
    onMessage { message ->
        if (headers["foo"] == "bar") {
            send("baz")
        } else {
            send(message)
        }
    }
    onError { exception: Exception ->
        println("Error $exception")
    }
    onClose { statusCode: Int, reason: String ->
        println("Terminating with status $statusCode and reason $reason")
    }
}
```

Thoughts on this? Any functionality that is missing or can be improved in some way?

**Comment by jaguililla** [comment]
That's a really clean API. However, I've got some suggestions :)

* For this feature to be consistent with the rest of the API, I guess the `message` parameter on the `onMessage` block could be included in the `MessageCall` (to give it a tentative name) leaving the block as:

```kotlin
onMessage {
    if (headers["foo"] == "bar") {
        send("baz")
    } else {
        send(message) // This would mean `this.message` really, `this` being `MessageCall` in this context
    }
}
```

* `onError` could receive an Exception type as the regular HTTP verbs to allow multiple handlers with different Exceptions.

* `onClose` would be called after terminating a client connection (by the server or the client), right? in this case, i don't know if the server would receive the statusCode and reason from the client. Or on the contrary, send these parameters to the client (or both scenarios are possible):

    * If client closes connection with a code and reason (I haven't check if this is feasible or not), then those parameters could be on the `CloseCall` making them available directly in the block.
    * If server closes connection with a code and reason. The way this is defined for other HTTP methods is in the `send` method. We could mimic that very same behaviour with `CloseCall.send(code: Int, reason: String)`
    * If both options are possible. We could include both.

Great job! really easy API to grasp. Tell me what you think about these ideas/proposals!

**Comment by BikramjeetSingh** [comment]
Could you please clarify what you meant in your 2nd point? I'm not sure I understood it very well.

Regarding your 3rd point, the client does not send any statusCode and reason when closing. I believe those are only for handling connection closures on the server side. In case the client closes the connection, the underlying framework will pass some default status code of its own to our application in the `onClose` callback. For example, in the case of Jetty, it passes the statusCode 1005 and reason as `null` in case the connection was closed by the client.

In case the server closes the connection and passes some statusCode and reason, those are reflected correctly in the onClose callback. For example, if we do ...

```kt
onMessage { message ->
    if (/* some condition */) {
        close(1001, "Some reason")
    }
}
onClose { statusCode, reason ->
    println("Closed with status $statusCode due to $reason")
}
```

... the output is `Closed with status 1001 due to Some reason`. However, these values are not sent to the client. Basically, the statusCode and reason values are only used within the server process and are never sent outside, by default.

**Comment by jaguililla** [comment]
Ok, now I understand how it works (and see it is different from usual HTTP requests).

I see your approach is valid, however, I would like to include the `message`, the `statusCode` and `reason` fields inside the handler's session instead them being passed as parameters to the callback block (to be consistent with HTTP handlers).

Do you think you can come up with a solution that takes care of this style preference? If you think is not worthy to explore this possibility, you can proceed as your suggested solution (that fulfills the requirements and it's ease to use/understand).

**Comment by BikramjeetSingh** [comment]
Definitely, I can see your point about keeping the style consistent with the HTTP handlers code, and I think it is valid. I will modify the API so that it contains `message`, `statusCode` and `reason` as fields rather than as parameters.
