### ISSUE TITLE
Simple command line arguments parsing

### ISSUE THREAD

**Issue by jaguililla** [hexagonkt/hexagon#403]
The purpose of this task would be to implement a minimum set of features to handle command line arguments properly without having to rely on a third party library like [picocli](https://github.com/remkop/picocli) or [jopt-simple](https://jopt-simple.github.io/jopt-simple).

The goal would be to provide the most used features to be used out of the box. Users who need all features, could go for an external library, but at Hexagon core there should be a minimum to parse arguments and display help messages and errors.

The features would be:
* Allow the definition of cli arguments. I.e., `data class Option<T : Any>(val shortName: Char?, val longName: String?, val description: String, val optional: Boolean, val type: KClass<T> = String::class, val defaultValue: T)`
* A function to parse an array of arguments with a given array of options: `fun parse(options: List<Option<*>>, vararg args: String): Map<Option, List<*>)`.
* Parse should fail if unkown parameter is passed.
* Another function to generate a help message based on the defined options (maybe on a class with the function described above).
* The allowed options format would be a subset of [posix standard](https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html)
  * Long parameters with values: `--name value` or `--name`
  * Short parameters clustered: `-alts` > `-a -l -t -s`
  * Short parameters with values: `-a value`

Things to consider:
* Does the OS takes care of the parameters scaping always? I.e., `'value with spaces'`, `"another value with $variable"`?

Previous work:
* In the settings processing, there was a very limited parameter parsing. You can check it out [here](https://github.com/hexagonkt/hexagon/blob/settings/hexagon_settings/src/main/kotlin/CommandLineArgumentsSource.kt).

Requirements:
* No external libraries.
* Short and simple (3 or 4 classes in a package at most).
* Extensive test set to cover all cases (there is a lot of corner cases).

If requirements are too complex to achieve, we can always discard this task and don't provide that functionality. I'm not sure 100% if the toolkit should including this. Trade offs are:
* Allow minimum features to develop a wide range of programs but adding more complexity and not being able to provide a viable alternative to 3rd party libraries.
* Focus on do the least features (don't be a bloated toolkit) and let the user select other specialized libraries for things not covered by Hexagon.

What do you think?

**Comment by pedro-cze** [comment]
Well, I would recommend not to reinvent the wheel :smile_cat: but providing some basic implementation according to requirements above seems reasonable. There will be a lot of to test though.

**Comment by jaguililla** [comment]
Ok, if you feel like it is challenging and funny to do for you... Go ahead!

Let's see how many functionality can be made without making a big and/or complex development.

However, if the functionality becomes big, it can always be moved to another module outside *Hexagon Core*.

I will wait until your confirmation to assign this task to you. Just let me know :)

**Comment by pedro-cze** [comment]
Ok, I will take this one, thanks. :)

**Comment by jaguililla** [comment]
All yours... Thanks!

**Comment by ibado** [comment]
Hi @jaguililla, I'm interesting in taking this one? Is @pedro-cze still woriing on it?

**Comment by Speedro** [comment]
Hi @ibado feel free to take it.

**Comment by jaguililla** [comment]
Hello @ibado, as @Speedro (I'm assuming it is the same person than @pedro-cze, at least, the account names are the same 🙂) is ok with that, I'll assign the task to you.

If you have any doubts, suggestions, etc. Just let me know and I'll be happy to help you if it's in my hands.

Happy coding!

**Comment by jaguililla** [comment]
Hello @ibado, as @Speedro (I'm assuming it is the same person than @pedro-cze, at least, the account names are the same 🙂) is ok with that, I'll assign the task to you.

If you have any doubts, suggestions, etc. Just let me know and I'll be happy to help you if it's in my hands.

Happy coding!

**Comment by jaguililla** [comment]
Hello @ibado, as @Speedro (I'm assuming it is the same person than @pedro-cze, at least, the account names are the same 🙂) is ok with that, I'll assign the task to you.

If you have any doubts, suggestions, etc. Just let me know and I'll be happy to help you if it's in my hands.

Happy coding!

**Comment by jaguililla** [comment]
Hello @ibado, as @Speedro (I'm assuming it is the same person than @pedro-cze, at least, the account names are the same 🙂) is ok with that, I'll assign the task to you.

If you have any doubts, suggestions, etc. Just let me know and I'll be happy to help you if it's in my hands.

Happy coding!

**Comment by jaguililla** [comment]
Hello @ibado, as @Speedro (I'm assuming it is the same person than @pedro-cze, at least, the account names are the same 🙂) is ok with that, I'll assign the task to you.

If you have any doubts, suggestions, etc. Just let me know and I'll be happy to help you if it's in my hands.

Happy coding!

**Comment by ibado** [comment]
Hi @jaguililla I've been thinking in a different way of defining arguments.
Instead of using a data class Options<T>, a KClass can be passed as arguments Template:
```kotlin
fun <T> parse(argumentsClass: KClass<T>, args: Array<String>): Result<T>
```
So a sample usage would be:
```kotlin
data class Args(val verbose: Boolean, val name: String)
val args: Args = parse(Args::class, arrayOf("--verbose", "true", "--name", "Ignacio")
```
And some simple annotation can be used for special configuration, something like this:
```kotlin
data class Args(@ShortName("v") val verbose: Boolean, val name: String)
val args: Args = parse(Args::class, arrayOf("-v", "true", "--name", "Ignacio")
```
What you think? please LMK :slightly_smiling_face:

**Comment by jaguililla** [comment]
That proposal seems very convenient to me, very easy to use and straightforward to understand by the users... However, there are some points I would like to note:

* The parameters are only one source of many in which the application config could come.
* Therefore, parsing them to a target class would pose the problem of having to integrate the other sources, priorities, etc.
* Due to the reason above, I was thinking on the parameters parsing quite as a primitive that could be combined with the other configuration sources (that is environment variables and system properties)
* There is also a problem with native image generation (not a stopper, but an inconvenience) and that is relying on reflection to parse the program parameters, that would force clients to take care of reflection configuration to create native images, while skipping reflection would result in an easier way of creating GraalVM native images without adding configuration by library users.

What do you think about these trade-offs?

**Comment by ibado** [comment]
Hi again! I get your point of view, that makes total sense.
Said that, I feel that your original proposal could be a little awkward in terms of user experience, since you'd need to cast the values in the resulting map:
```kotlin
    val argumentOpt = Option('a', "argument", "some description", false, String::class, "no value")
    val verboseOpt = Option('v', "verobse", "verbose mode", true, Boolean::class, false)
    val options = listOf(argumentOpt, verboseOpt)
    val result = parse(options, *args)
    
    val argument = result[argumentOpt] as String
    val verbose = result[verboseOpt] as Boolean
```
That would be okay or am I missing something here? :thinking: 

Another potential issue that I'm not sure can be done without reflection is having an `Option` of non-primitives types. But acording your previous comment I guess that's not something we necessarily want to have, right?

Please LMK what you think. Or if you come up with another idea :slightly_smiling_face:

**Comment by ibado** [comment]
Hi @jaguililla, have you been able to take a look at this?

**Comment by jaguililla** [comment]
Sorry for the delay... The code you set as a sample could be a little verbose, I agree. 

However, on top of the general cases, you can add some syntactic sugar in the form of utility classes / functions. I.e.:

```kotlin
val argumentOpt = Option('a', "argument", "some description", false, String::class, "no value")
val verboseOpt = Option('v', "verobse", "verbose mode", true, Boolean::class, false)
val options = listOf(argumentOpt, verboseOpt)
val result = parse(options, *args)
    
val argument = result[argumentOpt] as String
val verbose = result[verboseOpt] as Boolean

// Could become

val options = listOf(
    // Optional > true as it has a default value
    option<String>('a', "argument", "some description", "default")
    // No default, so it can be required or not
    option<String>('b', "argument2", "some description", optional = false)
    // We can define a 'flag' utility to describe the boolean option usual case 
    flag('v', "verbose", "verbose mode", defaultValue = false)
)
val result = parse(options, *args)

// Type inference can be used to avoid casting (maybe not with the '[]', not sure)    
val argument: String = result['a']
val verbose: Boolean = result["verbose"]
```

That could be accomplished just by adding some utility code on top of the general model definitions (the verbose ones).

From this point, the approach could be:

1. Write the more general code (the bulky one).
2. Add some syntactic sugar for ease of use.
3. The annotation processing can be built on top of that. However, this should happen in a different module, as this implies the use of reflection and using it should be a choice of the user (and not us, the library developers).

Would that make sense? My point is to provide functionality in layers, adding abstractions over the "low level" classes and letting the library's users decide which layer use.

And layers that would imply use of external libraries should be outside the core (reflection is one example).

**Comment by ibado** [comment]
Hi @jaguililla, I agree with you. The approach you proposed sounds the most reasonable way to proceed.

Talking about the "syntax sugar" part, I was specially worried about the **casting** part. the rest doesn't look bad in terms of boilerplate level.
I'm pretty sure the "type inference" won't work in the sample code you wrote.
An alternatvie to build on top of that could be to wrap the resulting map in an object that do the casting:
```kotlin
class Options(private val values: Map<Option<*>, Any>) {
    fun <T : Any> get(option: Option<T>): T? {
        val value = values[option] ?: return null
        return option.type.cast(value)
    }
}

fun parse(options: List<Option<*>>, vararg args: String): Options

/==========================================================================

val options = listOf(stringOption, booleanOption)
val result: Options = parse(options, *args)

val arg1 = result.get(stringOption) // this would be of type String
val arg2 = result.get(booleanOption) // and this of type Boolean
```
Anyway, I'll start with step 1) the more general implementation. We'll see how the syntax sugar can be done latter :+1:
