### ISSUE TITLE
Add Rocker template engine

### ISSUE THREAD

**Issue by jaguililla** [hexagonkt/hexagon#49]
Implement [Rocker](https://github.com/fizzed/rocker) backend (as `com.hexagonkt.templates.pebble.PebbleEngine`).

**Comment by jitakirin** [comment]
Is this still up for grabs?

**Comment by jaguililla** [comment]
Yes it is. If you want to work on this one, assign it to yourself and move it to 'working' in [the panel](https://github.com/hexagonkt/hexagon/projects/1). If you can't, please let me know!

Thanks for your interest in the project! You can ask me whatever you need :)

**Comment by jitakirin** [comment]
Cool, I'll get started on this.
Unfortunately can't seem to assign it at all nor move it on the board.

**Comment by jitakirin** [comment]
@jaguililla quick question, or two ;)

I added a new `TEMPLATE_ENGINE` system setting to `hexagon_benchmark` (`com.hexagonkt.Benchmark`) and I want to add it to add it to `BenchmarkTest` as well, do we want all combinations of server engine, database engine and template engine or is it enough to test it with different server engines but only e.g. postgres, etc?

Also, what are the benchmark servers in `docker-compose.yml` used for? Should I add all the combinations there as well?

**Comment by jaguililla** [comment]
It is great if you integrate the new engine into the benchmark. But as I see it, it is a whole new task.

If you want, I can create another task explaining how the benchmark works (this module is used in [this public benchmark](https://www.techempower.com/benchmarks)).

The `docker-compose.yml` file is used to start containers with given DBs and engines in order for JMeter to benchmark the framework (check `load_test.jmx`).

**Comment by jitakirin** [comment]
Ah OK, I added it to the benchmark just to have some test for it 😄 but sure if you want to create a task I'll complete it properly so it's more useful.
