### ISSUE TITLE
Add WebSockets example

### ISSUE THREAD

**Issue by jaguililla** [hexagonkt/hexagon#592]
I.e.: https://javalin.io/tutorials/websocket-example

**Comment by abhishekabk5** [comment]
Hi, I would like to contribute here, 
In what way should I add the example? as a ReadMe file or a Template or something else?

**Comment by jaguililla** [comment]
Hello, and thanks for collaborating with this project! I've just created a repository to contain the example, you can fork it, implement the example, and file the PR there, this is the URL: https://github.com/hexagonkt/websockets_chat

Please note that web sockets is not the best tested part of the toolkit, if you find any problem, please tell me (or even better, file a bug 😉).

Thanks again and... Happy coding!

**Comment by abhishekabk5** [comment]
https://github.com/hexagonkt/websockets_chat/pull/1

**Comment by abhishekabk5** [comment]
Facing an issue here, not sure why

![Image](https://github.com/hexagonkt/hexagon/assets/25201587/a5700590-63c7-4f0d-a024-b3f1d8fc1f06)

As per postman docs, the response code should be 101 (switching protocols) and not 202 (accepted), and i believe that's connection is not being established.
Ref - https://youtu.be/H-7EZVj9D-k

**Comment by jaguililla** [comment]
Right now I'm not at home. Let me get back to you regarding this issue after Sunday 30th :)

However, please use the `http_server_netty` adapter (changing the dependency in the `gradle.build.kts` file) as the Jetty adapter don't support WS yet.

I'll create a different task to explicitly fail when you try to use a feature not supported by the chosen adapter, but right now it fails silently :(

**Comment by abhishekabk5** [comment]
Ok, got it. i'll try with that and let you know the progress

**Comment by abhishekabk5** [comment]
Great, it's working fine now. Now, to make a sample webpage for this.

**Comment by abhishekabk5** [comment]
I have added the sample page as well. Complete task PR: https://github.com/hexagonkt/websockets_chat/pull/1

**Comment by jaguililla** [comment]
Thank you for your contribution!

It would be great if the HTML page was served from the server (and connecting to `http://localhost:9090` take you to the chat's page). That could be done easily by moving the page to the resources and serving those static resources (there are examples on the documentation).

I'll merge it right now as it is, if you want to code the proposed changes you can file another PR. Thanks!

**Comment by abhishekabk5** [comment]
Hey, Great to see my PR merged! 
I would like to make the proposed changes. But I tried moving the page to the resources folder, but it didn't work, `http://localhost:9090` still shows up as 404. I must be missing something, Which example are you referring to?
Draft PR: https://github.com/hexagonkt/websockets_chat/pull/2

**Comment by jaguililla** [comment]
Sorry I though I had an example with that functionality :(

Here is the example code to serve a classpath directory over a resource: https://github.com/hexagonkt/hexagon/blob/develop/http/http_test/src/main/kotlin/com/hexagonkt/http/test/examples/FilesTest.kt#L56
