### ISSUE TITLE
Callback to return an OpenAPI example response

### ISSUE THREAD

**Issue by jaguililla** [hexagonkt/hexagon#655]
Create a callback that returns a response from an OpenAPI spec. The spec would be provided with a URL.

The response will be fetched from the spec based on the method, path and the `X-Example-Response` header. If no header is provided, the first example will be picked.

This callback may be used in the dynamic server to return valid responses of a third party API mocked from its spec.

Check functionality in `com.hexagonkt.http.test.openapi` (currently outdated).

Callbacks already developed in the `http/http_server` module (on the `com/hexagonkt/http/server/callbacks` package) can be used as reference for development and testing of such components.

The callback should be added to the `http/rest_tools` module on the `com.hexagonkt.http.test.openapi` package.

For information on how to build the project and pass the tests please refer to the [contributing guide](https://github.com/hexagonkt/hexagon/contribute).

If you have any question or suggestion, please feel free to use this issue's comments to discuss them :wink:

**Comment by Sauhardstark** [comment]
Hi, any chance I could pick this up ?

**Comment by jaguililla** [comment]
Hi @Sauhardstark of course you can, I'll assign it to you and update the task.

As a hint, take a look at the `OpenApiHandler` class that did the same for a previous version of the toolkit. However, for this version, the `OpenApiHandler` functionality will be split in different callbacks (being this one of them).

Just take your time, and remember you can always reach me here or on the Kotlin Slack.

Thank you for your contribution... And happy coding!

**Comment by Sauhardstark** [comment]
Hi, I'm trying to join the Hexagon Slack but it requires a "@jetbrains.com" email. Can you help a little ?

**Comment by jaguililla** [comment]
Sorry for the delay... You can join the Kotlin Slack by requesting access here: https://surveys.jetbrains.com/s3/kotlin-slack-sign-up they usually approve access quickly... See you there :wink:

**Comment by jaguililla** [comment]
Hello, is there any progress on this task?

**Comment by jaguililla** [comment]
This feature is optional and will be dismissed by now.
