### ISSUE TITLE
Restructure Benchmark to test different configurations in a single JVM process

### ISSUE THREAD

**Issue by jaguililla** [hexagonkt/hexagon#97]
Provide specific routes for some tests instead full containers.

It could be done using one container by server (Jetty, Undertow, Resin...) and each of them will have routes for every combination of DB and template engine. E.g:

http://jetty-container:5010/mongodb/pebble/fortunes
http://jetty-container:5010/mongodb/rocker/fortunes
http://jetty-container:5010/postgresql/pebble/fortunes
http://jetty-container:5010/postgresql/rocker/fortunes
http://jetty-container:5010/postgresql/rocker/fortunes

**Comment by jitakirin** [comment]
OK, I made some progress, implemented tests with path parameters for DB engines, so now `Benchmark.kt` connects to all DBs and which one is used depends on first element of the path, like in your examples.

I now have a couple of questions 😃 

1. do you still want to preserve the possibility of defining which engines get connected to using `DBSTORE` env variable?

2. test combinations and URLs that get hit are also defined in `build.gradle` for `hexagon_benchmark` but I can't quite see, what are these used for? 

3. how are JMeter tests triggered?

**Comment by jaguililla** [comment]
Sorry for the delay:

1. You can get rid of DBSTORE env variable. The less the code the better.
2. This is a bit obscure (sorry for that). The explanation is: the `hexagon_benchmark` module is the code for [Techempower Benchmarks](https://www.techempower.com/benchmarks) (TFB from now on). But with subtle differences to be able to run inside the project. `build.gradle` generates the code merged in TFB with the `tfb` task and the routes are part of this setup.
3. JMeter tests are run manually (they don't run in the build process). You have to start docker compose: `docker-compose up -d` in the project root, open `load_test.jmx` in JMeter interface, change settings in the root of the configuration (number of concurrent connections, ports and so on) and execute them.

Please don't hesitate to ask anything, I will be more than happy to help. And thanks for taking care of this task!

**Comment by jitakirin** [comment]
OK, so IIUC generally these things are fairly independent: `BenchmarkTest.kt` is for unit testing, gradle `tfb` task and related things are for TFB and `docker-compose.yml` is for JMeter tests; they all rely on `Benchmark.kt` which provides the server under test but that's it. Is that correct?

If so, I have a good idea where I'm going next :)

**Comment by jaguililla** [comment]
Yes, it is. But `docker-compose.yml` is also used for "unit" testing now (until I figure out how to start mongodb and rabbit inside the tests).

**Comment by jitakirin** [comment]
Oh, yes, the databases, that's right. Well, docker is really good for this kind of stuff as it doesn't require anything on the host and doesn't conflict with anything else on the system (like other mongos or postgreses) ;)

**Comment by jitakirin** [comment]
Another quick question, currently there are no benchmarks with rocker for TFB, shall I add it to the combinations or leave it out for now?
